---
- block:
    - name: builds dir
      ansible.builtin.debug:
        msg: "{{ build_json_dir }}"

    - name: read the build JSON file
      set_fact:
        build_json: "{{ lookup('file', build_json_dir +'/' + project_name + '.json') | from_json }}"

    - name: image tag
      ansible.builtin.debug:
        msg: "{{ build_json.builds[0].tag }}"

    - name: run skaffold deploy
      run_once: true
      ansible.builtin.command:
        chdir: "{{ de_releases_dir }}/services/{{ project_name }}"
        cmd: skaffold deploy --namespace "{{ ns }}" --build-artifacts "../../builds/{{ project_name }}.json" --force --kubeconfig "{{ lookup('env', 'KUBECONFIG') }}"
  tags:
    - deploy
