# Deploys a single service.
#
# Used for CI/CD
#
# Variables:
#   project: the name of the service to deploy.
#
# Environment Variables:
#   KUBECONFIG: the path to the kubeconfig to use for the cluster.

---
- hosts: k8s_bastions
  run_once: true
  gather_facts: false
  become: false
  tasks:
    - ansible.builtin.include_role:
        name: services
        tasks_from: main
      vars:
        project_name: "{{ project }}"
      tags:
        - deploy
